// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAspT8YQozsM1QJQP7v4WG5h2FihcFS1VA',
    appId: '1:312832825016:web:f11e0d4a9ef2187165c64d',
    messagingSenderId: '312832825016',
    projectId: 'saya-terlalu-project',
    authDomain: 'saya-terlalu-project.firebaseapp.com',
    storageBucket: 'saya-terlalu-project.firebasestorage.app',
    measurementId: 'G-DWCRXPRMET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgka-u9obzrQxe-_4PHuz580KAJ-Nbrfc',
    appId: '1:312832825016:android:994b8b03cd249d3765c64d',
    messagingSenderId: '312832825016',
    projectId: 'saya-terlalu-project',
    storageBucket: 'saya-terlalu-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYsS9z5Ix-spbHVZ3uR9VFDmqKp860njg',
    appId: '1:312832825016:ios:580f49a14702e86f65c64d',
    messagingSenderId: '312832825016',
    projectId: 'saya-terlalu-project',
    storageBucket: 'saya-terlalu-project.firebasestorage.app',
    iosBundleId: 'com.example.belajarppkdIhsan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYsS9z5Ix-spbHVZ3uR9VFDmqKp860njg',
    appId: '1:312832825016:ios:580f49a14702e86f65c64d',
    messagingSenderId: '312832825016',
    projectId: 'saya-terlalu-project',
    storageBucket: 'saya-terlalu-project.firebasestorage.app',
    iosBundleId: 'com.example.belajarppkdIhsan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAspT8YQozsM1QJQP7v4WG5h2FihcFS1VA',
    appId: '1:312832825016:web:193fcad9cf6760f765c64d',
    messagingSenderId: '312832825016',
    projectId: 'saya-terlalu-project',
    authDomain: 'saya-terlalu-project.firebaseapp.com',
    storageBucket: 'saya-terlalu-project.firebasestorage.app',
    measurementId: 'G-152VL6SW5B',
  );
}
